[tool.poetry]
name = "${template:app_name_underscore}"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.9"
Flask = "^3.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pytest-flask = "^1.2.0"
uw-it-build-fingerprinter = "^0.2.6"
black = "^22.6.0"
flake8 = "^5.0.2"

[[tool.poetry.source]]
name = "iam-pypi"
url = "https://us-python.pkg.dev/uwit-mci-iam/iam-pypi/simple/"
priority = "explicit"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
# coordinated with setup.cfg max-line-length
line-length = 119
