# To use this, paste it into a flux-monitored repository (e.g., uwit-iam/gcp-k8)
# and update any values that need updating. Read the comments below
# to know what needs to be updated. Look for 'UPDATE'
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: ${template:app_name_hyphen}-policy
  namespace: default # must be 'default' in MCI, even if app itself is not in default
spec:
  imageRepositoryRef:
    name: ${template:app_name_hyphen}-gar
  filterTags:
    pattern: '^deploy-dev.(?P<ts>[0-9\.]+)\.v.+$'
    extract: '$ts'
  policy:
    alphabetical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: ${template:app_name_hyphen}-gar
  namespace: default # must be 'default' in MCI, even if app itself is not in default
spec:
  image: us-docker.pkg.dev/uwit-mci-iam/containers/${template:app_name_hyphen}
  interval: 2m0s
  secretRef:
    name: flux-mci-registry-credential
