# For a full list of configuration available for the `values`
# section, refer to
# https://github.com/uw-iti-app-platform/helm-charts/blob/main/basic-web-service/values.yaml
#
# To use this, paste it into a flux-monitored repository (e.g., uwit-iam/gcp-k8)
# and update any values that need updating.
#
# This is very minimal configuration!
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ${template:app_name_hyphen}
  namespace: default
spec:
  values:
    app:
      name: ${template:app_name_hyphen}
      clusterDomain: iamdev.s.uw.edu
    replicaCount: 1
    ports:
      # 5000 for flask, 8000 for django, 8080 for tomcat, ...
      containerHttpPort: 5000
    service:
      port: 80
    ingress:
      enabled: true
      # uncomment these 2 lines to enable SAML SSO
      # in addition you need to configure SPReg to register a new service provider
      # - binding: urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST
      # - location: https://YOUR_APP...uw.edu/saml/login
      # https://iam-tools.u.washington.edu/spreg
      #saml:
      #  enabled: true
      # uncomment this line to restrict access to effective members of this group
      # note you need to configure the SPReg to release this group
      #  gwsGroupid: fooGroup

      # uncomment this to enable TLS. You'll get an ACME cert automagically
      #tls: true
    resources:
      requests:
        memory: "32M"
        cpu: "50m"
      limits:
        memory: "64M"
        cpu: "100m"
    image:
      name: us-docker.pkg.dev/uwit-mci-iam/containers/${template:app_name_hyphen}
      tag: latest  # {"$imagepolicy": "default:${template:app_name_hyphen}-policy:tag"}

  chart:
    spec:
      chart: basic-web-service
      version: 0.3.6
      sourceRef:
        # This assumes there is already a helm-chart-repository defined in
        # your flux-monitored repository (e.g., gcp-k8)
        kind: HelmRepository
        name: helm-chart-repository
        namespace: default
  interval: 1m0s
