name: Pull request validation workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
    paths-ignore:
      - '**.md'

env:
  GCR_TOKEN: ${{ secrets.GCR_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  STEP_SCRIPTS: ${{ github.workspace }}/.github/steps/pull-request

jobs:
  update-pr-branch-version:
    runs-on: ubuntu-latest
    outputs:
      new-version: ${{ steps.update-version.outputs.new-version }}
    steps:
      - name: Python Poetry Action
        uses: abatilo/actions-poetry@v2.1.4

      - uses: uwit-iam/actions/require-semver-guidance-label@0.1
        id: guidance
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: uwit-iam/actions/update-pr-branch-version@0.1
        with:
          github-token: ${{ env.GITHUB_TOKEN }}
          version-guidance: ${{ steps.guidance.outputs.guidance }}
        id: update-version

  validate-image-quality:
    permissions:
      contents: write
      id-token: write
      pull-requests: write

    needs: [update-pr-branch-version]
    runs-on: ubuntu-latest
    env:
      APP_VERSION: ${{ needs.update-pr-branch-version.outputs.new-version }}
      pr_tag: pull-request-${{ github.event.pull_request.number }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: abatilo/actions-poetry@v2.1.4
      - run: |
          sudo apt-get -y install jq
          poetry install
        id: configure
        name: Set up environment

      - uses: UWIT-IAM/actions/configure-gcloud-docker@0.1
        with:
          gcloud-token: ${{ secrets.GCR_TOKEN }}

      - run: |
          ./scripts/build.sh \
            -t pull-request-${{ env.PR_TAG }} --cache

      - run: docker push gcr.io/uwit-mci-iam/${template:app_name}:${{ env.pr_tag }}

      - name: Run validation checks and tests
        run: |
          poetry run pytest
          poetry run flake8
          poetry run black --check .
        id: run-validations

      - uses: mshick/add-pr-comment@v1
        env:
          image: gcr.io/uwit-mci-iam/${template:app_name}:${{ env.pr_tag }}
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
          allow-repeats: false
          message: |
            Download and run the latest build with:

            ```
            docker pull ${{ env.image }}
            docker run -it ${{ env.image }}
            ```
