name: Release on push to `main`
on:
  push:
    branches:
      - main
    paths:
      - pyproject.toml
jobs:
  check-publishability:
    runs-on: ubuntu-latest
    outputs:
      publishable: ${{ steps.check.outputs.publish }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      # Only publish if the version has changed; otherwise, we would be
      # re-publishing existing stuff without updating the version, and that
      # could cause problems.
      - run: |
          set -x
          publishable=false
          diff=$(git diff HEAD:pyproject.toml HEAD~1:pyproject.toml)
          echo "$diff" | grep '+version ='
          if [[ "$?" == "0" ]]
          then
            publishable=true
          fi
          echo "::set-output name=publish::${publishable}"
        name: Check if the change should be published
        id: check
  build-and-publish:
    needs: [check-publishability]
    if: needs.check-publishability.outputs.publishable == 'true'
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: abatilo/actions-poetry@v2.1.3
      - run: poetry config virtualenvs.create false
      - run: sudo apt-get -y install jq
      - name: Log in to the Google container registry
        if: false
        # UPDATE:
        # If you are using gcr.io to host your image,
        # remove the `if: false` line, otherwise just delete this step.
        run: ./.github/scripts/gcr-login.sh
        env:
          # UPDATE: If this repository is not in the UWIT-IAM
          # org, you must ensure this secret exists, or update this
          # value to use a secret that does exist. The token
          # should be base64 encoded, and needs to be created by an
          # Aux project administrator.
          #
          # If you are running inside the UWIT-IAM namespace,
          # this is available for all repositories to use.
          GITHUB_TOKEN: ${{ secrets.GCR_TOKEN }}
      - name: Log in to the GitHub Container registry
        if: false
        # UPDATE:
        # If you are using Github packages to host your image,
        # remove the `if: false` line, otherwise just delete this step.
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          version=$(poetry version -s)
          echo "::notice::Publishing version ${version}"
          echo "::set-output name=version::${version}"
        id: get-version
      - run: poetry install
      - run: |
        if: false
        # UPDATE:
        # If you intend to publish your repository to PyPI, you should
        # follow the instructions in the readme under
        # 'Authenticating to PyPI' to set up your repository with correct permissions.
        # Once you do that, you can delete the `if: false` line to enable this step.
        # If you don't intend to do that, you can delete this step.
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry build -n
          poetry publish -n
      - run: >
          echo "::notice::to finish configuring this workflow, follow the
          instructions for each section in the workflow file flagged with UPDATE."
